version: '3.7'

services:

  database:
    image: postgres
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: 321654987a
      POSTGRES_DB: Hacktus
      POSTGRES_USER: konnekt
    networks:
      - konnekt

  nginx:
    image: nginx:1.19.1-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - konnekt

  app:
    build:
      args:
        user: frales
        uid: 1000
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: hacktus-backend
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - konnekt
    depends_on:
      - nginx
      - database

networks:
  konnekt:
    driver: bridge
